#!/bin/bash

# copy the latest website content out to S3
for file in `find . -type f`; do
    echo "pushing ${file:2}";
    aws --region us-east-1 s3api put-object \
        --bucket soniaszeton.com \
        --key ${file:2} \
        --body ${file}
done

